# Generated by Django 5.1.3 on 2025-12-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Сипаттама')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сома')),
                ('transaction_type', models.CharField(choices=[('income', 'Кіріс'), ('expense', 'Шығыс')], max_length=10, verbose_name='Түрі')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Күні')),
            ],
        ),
    ]
